//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thebourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrails
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
