//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thebourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public bool isCancel { get; set; }
        public string ReservedBy { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public string OrNumber { get; set; }
        public string TransactionId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Seats Seats { get; set; }
        public virtual AspNetUsers UsersReservedBy { get; set; }
    }
}
